{{- if eq .Values.cloudProvider "aws" }}
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: efs.csi.aws.com
spec:
  attachRequired: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
{{- end }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
{{- if eq .Values.cloudProvider "aws" }}
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.id }}
{{- else if eq .Values.cloudProvider "azure" }}
  storageClassName: ""
  azureDisk:
    kind: Managed
    diskName: {{ .Values.managedDisk.name }}
    diskURI: {{ .Values.managedDisk.uri }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
{{- if eq .Values.cloudProvider "aws" }}
  storageClassName: efs-sc
{{- else if eq .Values.cloudProvider "azure" }}
  storageClassName: ""
{{- end -}}