apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfig | b64enc }}