apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-internal-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jenkins-master-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: port-8080
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: port-50000