apiVersion: v1
kind: Service
metadata:
  name: hello-world-aspnetcore-internal-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: hello-world-aspnetcore-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: port-80