apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
  name: jenkins-agent
  namespace: {{ .Values.namespace }}
spec:
  imagePullSecrets:
    - name: container-registry-secret
  containers:
    - name: jnlp
      image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      workingDir: /home/jenkins
      env:
        - name: JENKINS_URL
          value: http://jenkins-master-internal-svc.{{ .Values.namespace }}:8080
        - name: JENKINS_TUNNEL
          value: jenkins-master-internal-svc.{{ .Values.namespace }}:50000
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: host-docker-sock
        - mountPath: ~/.kube
          name: cloud-fileshare
      resources:
        requests:
          cpu: 500m
          memory: 0.5Gi
        limits:
          cpu: 1000m
          memory: 1Gi
  volumes:
    - name: host-docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: cloud-fileshare
    {{- if eq .Values.cloudProvider "aws" }}
      persistentVolumeClaim:
        claimName: deployment-kubeconfig-pvc
    {{- else if eq .Values.cloudProvider "azure" }}
      azureFile:
        secretName: azure-fileshare-secret
        shareName: deployment-kubeconfig
        readOnly: true
    {{- end -}}