library identifier: 'cicd',
    retriever: modernSCM([
        $class: 'GitSCMSource',
        remote: 'https://github.com/ankursoni/kubernetes-extension-fortio.git',
        credentialsId: 'github-credentials'
    ])

cicd("hello-world-aspnetcore")